-- AlterTable
ALTER TABLE "Game" ADD COLUMN "categories" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Game" ADD COLUMN "mechanisms" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Game" ADD COLUMN "families" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Game" ADD COLUMN "designers" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Game" ADD COLUMN "artists" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
